name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Clear cache
        run: |
          yarn cache clean
          rm -rf node_modules
          rm -f yarn.lock

      - name: Install Linux rollup package
        run: yarn add @rollup/rollup-linux-x64-gnu

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile --ignore-optional
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Generate static site
        run: yarn generate
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Add .nojekyll and 404.html
        run: |
          echo > .output/public/.nojekyll
          cp .output/public/index.html .output/public/404.html

      - name: Fix file permissions
        run: |
          chmod -R 755 .output/public

      - name: List files before deploy
        run: ls -alR .output/public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'  